ProEpiDesenvolvimento/guardioes-app

- ios/Podfile.lock
- ios/guardioesapp/Info.plist
Alteração nas definições do app IOS para manter o tema "Light".
> fix darkMode IOS

- src/components/principal/Home.js
O nome do usuário não irá mais aparecer completo na tela Home, o que podia causar bugs quando o nome era grande demais ou a tela muito pequena.<br>
**Checklist**
> Fix user name in Home screen

- .travis.yml
Explicar as mudanças feitas nesse pull request, referenciando as issues que foram resolvidas com esse pull request e os responsáveis por ela.<br>
Ex: Foi feito o documento A (#12 - @fulano e @ciclano) para que possamos visualizar melhor o contexto do projeto e modificado o documento B (#28 - @fulano) para atualizar proposta de projeto;<br>
**Checklist**
> Add pull requests to CI

- src/components/principal/Conselho.js
- src/components/principal/Noticias.js
A página "notícias" foi atualizada para o twitter do Guardiões da Saúde.
**Checklist**
> Change Twitter page

- src/components/principal/Perfil.js
Esse PR adiciona o campo da instituição na pagina de editar familiares.
> Adding school field to edit household page

- src/components/principal/Perfil.js
Este Pull Request corrige a [Issue #78](https://github.com/proepidesenvolvimento/guardioes-app/issues/78). Arrumando os campos _Data de Nascimento_ e _Raça_ da edição de households.<br>
**Checklist**
> Fix fields Birthdate and Race on edit household page

- src/components/principal/badReport.js
Arruma a lógica da mensagem para aparecer em todos os casos em que é necessária.<br>
**Checklist**
> Fix message

- locales/en.js
- locales/es.js
- locales/pt.js
- src/components/telainicial/getToken.js
Conserta erro de grafia e traduz as paginas de recuperação de senha.
Resolve issue #86 
**Checklist**
> Fix typos and translate password recovery

- src/components/principal/Household.js
- src/components/principal/Perfil.js
Adiciona o campo de grupo de risco à pagina de registro de household, à modal de edição de household e à modal de edição do usuário.<br>
**Checklist**
> Adiciona o campo de grupo de risco ao household e à edição de usuário

- locales/en.js
- locales/es.js
- locales/pt.js
- package-lock.json
- src/components/principal/Household.js
- src/components/principal/Perfil.js
- src/components/telainicial/Registrar.js
Adiciona mensagem explicativa sobre grupos de risco no cadastro de usuário. (#95 - @emanuks)<br>
**Checklist**
> Adding risk group message on register

- src/components/principal/badReport.js
Foi editado a função de verificar síndromes e a de mostrar a mensagem da síndrome para o usuario. Agora é possível mostrar as mensagens da respectiva síndrome que o usuário mais se encaixar segundo lógica da api. A síndrome gripal é um caso isolado e, caso o usuario se encaixe nela, irá mostrar na tela um aviso perguntando se o usuário deseja compartilhar um card com outros usuários avisando sobre essa síndrome. <br>
Resolve issue #102
**Checklist**
> Generalizing syndromes messages

- README.md
- locales/en.js
- locales/es.js
- locales/pt.js
- package-lock.json
- src/components/principal/Household.js
- src/components/principal/Perfil.js
- src/components/telainicial/Registrar.js
- src/components/telainicial/getToken.js
- src/utils/brasil.js
Reverts proepidesenvolvimento/guardioes-app#110
> Revert "Fix/addingRAs"

- src/utils/brasil.js
Refazendo o PR #110 no ramo development
> Adding new RAs to brasil.js

- src/components/principal/Household.js
- src/components/principal/Perfil.js
- src/components/telainicial/Registrar.js
- src/components/userData/InstitutionSelector.js
Altera o sistema de input de instituições para o front-end de acordo com a nova mudança em como isso é tratado no back-end.
Resolve issue #112 e #119
**Checklist**
> Adapt instituition input to group model

- src/components/telainicial/Registrar/index.js
Conserta bug que impedia o usuário de registrar
**Checklist**
> Register bug in new design

- src/components/userData/InstitutionSelector.js
Tamanho do codigo de idenficação não tem mais tamanho necessário.
**Checklist**
> Remove id code length size limit

- src/components/navigation/drawerContentComponent.js
- src/components/navigation/navigator.js
- src/components/principal/Conselho/index.js
- src/components/principal/Conselho/styles.js
- src/components/principal/Diario/index.js
- src/components/principal/Diario/styles.js
- src/components/principal/EditarPerfil/index.js
- src/components/principal/Home/index.js
- src/components/principal/Home/styles.js
- src/components/principal/Perfis/index.js
- src/components/principal/newNoticias/styles.js
- src/components/telainicial/Registrar/index.js
- src/components/userData/InstitutionSelector.js
Esse PR corrige o erro de usuários que se cadastraram sem data de nascimento, permitindo que eles corrijam o perfil e impedindo que novos usuários cometam o mesmo erro. A tela home agora é atualizada todas as vezes em que é aberta, permitindo que as alterações no perfil sejam vistas imediatamente; Perfis selecionados são memorizados e continuam selecionados após abrir o app outra vez. A tab bar foi melhorada para não aparecer bordas cinzas em nenhuma tela.<br>
**Checklist**
> Fix User birthdate, User selected and Tab bar navigation

- src/components/navigation/drawerContentComponent.js
- src/components/navigation/navigator.js
- src/components/principal/Conselho/index.js
- src/components/principal/Conselho/styles.js
- src/components/principal/Diario/index.js
- src/components/principal/Diario/styles.js
- src/components/principal/EditarPerfil/index.js
- src/components/principal/Home/index.js
- src/components/principal/Home/styles.js
- src/components/principal/Perfis/index.js
- src/components/principal/newNoticias/styles.js
- src/components/telainicial/Loading/index.js
- src/components/telainicial/Login/index.js
- src/components/telainicial/Registrar/index.js
- src/components/userData/InstitutionSelector.js
Muda a forma em que o cálculo de participação é contabilizado na tela Diário e também corrige bugs desse processo.<br>
O PR da API [#160](https://github.com/proepidesenvolvimento/guardioes-api/pull/160) precisa estar subido.<br>
**Checklist**
> Fix User participation in Diary

- src/components/navigation/drawerContentComponent.js
Changing validation to vigilance page to show for user from school_unit_id to group_id
> Changing validation to vigilance page to show for user

- src/components/principal/Dicas/index.js
- src/components/principal/Dicas/styles.js
Nessa issue foram feitas as seguintes alterações na aba de Dicas do aplicativo:
- Limitamos a área do texto de cada card, com o máximo de 3 linhas
- Fixamos o tamanho do card
- Ordenamos os cards de acordo com o tributo created_at
Issue relacionada: #173 
<br>
**Resultado**
**Checklist**
> Ordenação e organização da Aba dicas de Saúde

- locales/en.js
- locales/es.js
- locales/pt.js
- src/components/navigation/drawerContentComponent.js
- src/components/principal/Ajuda/index.js
- src/components/principal/Diario/index.js
- src/components/principal/Dicas/index.js
- src/components/principal/EditarPerfil/index.js
- src/components/principal/FAQ/index.js
- src/components/principal/Home/index.js
- src/components/principal/Mapa/index.js
- src/components/principal/Noticias/NoticiasComponent.js
- src/components/principal/Noticias/index.js
- src/components/principal/NovoPerfil/index.js
- src/components/principal/Perfis/index.js
- src/components/principal/Rumor/index.js
- src/components/principal/Sobre/index.js
- src/components/principal/TermosPoliticas/index.js
- src/components/principal/Tutorial/index.js
- src/components/principal/Vigilancia/index.js
- src/components/principal/badReport/index.js
- src/components/telainicial/ForgetPwd/index.js
- src/components/telainicial/Login/index.js
- src/components/telainicial/Registrar/index.js
- src/components/telainicial/TelaInicial/index.js
- src/components/userData/InstitutionSelector.js
- src/utils/MarkerClustering/ClusterMarker.js
- src/utils/selectorUtils.js
Todos os textos dos componentes principais foram convertidos em variáveis de internacionalização. Todos os arquivos principais tiveram seu código fonte alterado para a folha de estilo do projeto - ESLint.
**Issue**
#126 
**Critérios de Aceitação**
**Checklist**
> Completando as Traduções e Aplicando Folha de Estilo

- App.js
- src/api/contents.js
- src/api/household.js
- src/api/surveys.js
- src/api/user.js
- src/hooks/index.js
- src/hooks/user.js
Adiciona a refatoração das requisições da API e o começo do User Hook mas não implementa nenhum ainda.<br>
**Checklist**
> Add primary User Hook and refatorate API requests

- src/components/LeftMenu/index.js
Links nos botões para o twitter e instagram foram trocados para as redes da ProEpi.<br>
**Checklist**
> Change twitter and instagram share links

- src/api/groups.js
- src/components/LeftMenu/index.js
- src/components/LeftMenu/styles.js
- src/screens/principal/Noticias/index.js
Esse PR adiciona uma requisição no menu lateral para verificar se o usuário faz parte de um grupo que aderiu a Vigilância Ativa.<br>
**Checklist**
> Add Active Surveillance verification on LeftMenu

- src/screens/principal/Vigilancia/index.js
Esse PR adiciona um popup de alerta para o usuário para que ele insira todos os dados necessários para cadastro de vigilânci atival<br>
> Show pop-up if user don't insert name in vigilance

- src/hooks/user.js
- src/screens/principal/BadReport/index.js
- src/screens/principal/Home/index.js
Esse PR corrige bugs relacionados a localização na hora de enviar uma Survey.<br>
**Checklist**
> Fix location bugs

- ios/guardioesapp/AppDelegate.m
Corrige Splashscreen no iOS fazendo com que ela feche antes de que se tenha carregado todos os dados do usuário.<br>
**Checklist**
> Fix Splashscreen on iOS

- src/components/Autocomplete/index.js
- src/components/Autocomplete/styles.js
- src/components/Groups/InstitutionSelector.js
- src/screens/inicio/Login/index.js
- src/screens/inicio/Register/index.js
- src/screens/principal/Dicas/index.js
- src/screens/principal/Home/index.js
- src/screens/principal/Home/styles.js
Esse PR corrige alguns bugs para a release.<br>
**Checklist**
> Fix Release bugs

- locales/en.js
- locales/es.js
- locales/pt.js
- src/screens/principal/BadReport/index.js
Foi adicionado um alerta ao usuário quando o mesmo tenta enviar um report sem nenhum sintoma. Sendo assim não é possível o usuário enviar um report sem sintoma e evitando o bug encontrado. 
**Checklist**
> [BUG] report sem sintoma

- src/api/households.js
- src/navigation/AppStack.js
- src/screens/principal/NovoPerfil/index.js
Foi adicionado um botão no header da página de perfis que redireciona para a página de adicionar um novo perfil. Depois de adicionar o usuário vai ser redirecionado para a página home.
**Checklist**
> Adding households by Profile's page

- locales/en.js
- locales/es.js
- locales/pt.js
- src/screens/principal/BadReport/index.js
- src/screens/principal/Home/index.js
Corrige as mensagens e emojis ao reportar o estado de saúde, para diferenciar melhor a mensagem de sucesso e a de aviso.<br>
**Checklist**
> Fix reporting message

- src/screens/inicio/Register/index.js
- src/screens/principal/BadReport/index.js
- src/screens/principal/EditarPerfil/index.js
- src/screens/principal/Home/index.js
- src/screens/principal/NovoPerfil/index.js
Corrige bug das datas nos seletores do aplicativo. Deve ser testado com branch `fix/Dates` do guardioes-api.<br>
Como testar: Abrir perfis, editar data de nascimento de um familiar, salvar e verificar novamente se a data correta permanece. Repetir os passos com o usuário.
**Checklist**
> Fix moment.js dates

- src/screens/inicio/Register/index.js
- src/screens/principal/EditarPerfil/index.js
- src/screens/principal/NovoPerfil/index.js
Realiza mudanças na tela de Registrar, EditarPerfil e AdicionarPerfil após feedbacks no teste da aplicação.<br>
**Checklist**
> Fix Register

- src/api/vaccines.js
- src/hooks/user.js
- src/screens/principal/Home/index.js
- src/screens/principal/Vacinacao/index.js
Realiza mudanças na tela de Vacinação relacionadas a rota e o atributo de doses do user.<br>
**Checklist**
> Fix Vaccination

- locales/en.js
- locales/es.js
- locales/pt.js
- src/screens/principal/Rumor/index.js
- src/screens/principal/Vacinacao/index.js
- src/utils/formConsts.js
Remove o método de storeUser da tela de Vacinação, adiciona validação de Rumor e corrige feedback.<br>
**Checklist**
> Fix Vacinacao and Rumor

- src/screens/inicio/Register/index.js
- src/screens/principal/Home/index.js
- src/screens/principal/Vigilancia/index.js
Habilita visualização do telefone após fazer parte da Vigilância Ativa.
**Checklist**
> Fix Vigilance

- locales/en.js
- locales/es.js
- locales/pt.js
- src/components/NormalForms.js
- src/screens/inicio/Register/index.js
- src/screens/inicio/Register/styles.js
- src/screens/principal/Vigilancia/index.js
Adiciona modal com informações relacionadas a Gênero no cadastro.<br>
**Checklist**
> Add gender info

- src/screens/inicio/Register/index.js
- src/screens/principal/EditarPerfil/index.js
- src/screens/principal/NovoPerfil/index.js
Novidades no app: 
+ Corrige bug no cadastro quando não há categorias cadastradas
**Checklist**
> Development (3.2.8)

- .buckconfig
- android/app/build.gradle
- ios/guardioesapp.xcodeproj/project.pbxproj
- src/screens/principal/Diario/index.js
- src/screens/principal/Ranking/index.js
Novidades no app: 
- Corrige texto "dias seguido para dias seguidos" na tela Diário e Ranking
**Checklist**
> Development (2.3.9)

- android/app/build.gradle
- ios/guardioesapp.xcodeproj/project.pbxproj
- package.json
- src/components/NormalForms.js
- src/screens/principal/Quiz/index.js
- src/screens/principal/Vacinacao/index.js
- src/screens/principal/Vacinacao/styles.js
- src/screens/principal/Vigilancia/index.js
Novidades no app: 
- Alterações no comportamento do Quiz
**Checklist**
> Development (3.3.4)
